name: "Plugin CI/CD"

on:
  release:
    types: [created]
    
jobs:
  plugin:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x86
 
      - name: Compile plugin
        run: |
          cmake . --preset MP-Release
          cmake --build --preset MP-Release

      - name: Find plugin
        run: |
          $plugin_dll = Get-ChildItem *.dll -Recurse | Select-Object -First 1 -ExpandProperty FullName
          $plugin_dll = $plugin_dll.Replace((Resolve-Path ".").Path + "\", "")
          $plugin_dll = $plugin_dll.Replace("\", "/")
          echo "plugin_dll=$plugin_dll" >> $env:GITHUB_ENV
          echo "Found plugin path: $plugin_dll"

      - name: Upload plugin
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.md
          files: ${{ env.plugin_dll }}